name = "BasedDumps"
authors = ["William Herrera <wherrera@alahonua.com>"]
uuid = "808baba0-b719-11eb-2c94-1803250cf58a"
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"

[compat]
julia = "1"

[targets]
test = ["Test", "Suppressor"]
